dist: trusty
sudo: false
language: python
python:
  - "3.6"
before_install:
  - pip install flake8 pytest
install:
  - pip install .
script:
  - pytest hetmatpy
  - flake8 --max-line-length=120 hetmatpy
